<template>
    <my-page title="疫苗接种时间">
        <ui-article>
            <h2>一类疫苗</h2>
            <table>
                <tr>
                    <td>出生24小时内</td>
                    <td>乙肝疫苗—第一针；卡介苗—初种；</td>
                </tr>
                <tr>
                    <td>1月龄</td>
                    <td>乙肝疫苗—第二针；</td>
                </tr>
                <tr>
                    <td>2月龄</td>
                    <td>脊髓灰质炎糖丸—第一针；</td>
                </tr>
                <tr>
                    <td>3月龄</td>
                    <td>脊髓灰质炎糖丸—第二针；百白破疫苗—第一针；</td>
                </tr>
                <tr>
                    <td>4月龄</td>
                    <td>脊髓灰质炎糖丸—第三针；百白破疫苗—第二针；</td>
                </tr>
                <tr>
                    <td>6月龄</td>
                    <td>百白破疫苗—第三针；乙肝疫苗—第三针；A群流脑疫苗第一针；</td>
                </tr>
                <tr>
                    <td>8月龄</td>
                    <td>麻疹疫苗—第一针；</td>
                </tr>
                <tr>
                    <td>9月龄</td>
                    <td>A群流脑疫苗—第二针；</td>
                </tr>
                <tr>
                    <td>1岁</td>
                    <td>乙脑疫苗—初种；</td>
                </tr>
                <tr>
                    <td>1.5至2岁</td>
                    <td>百白破疫苗—加强；脊髓灰质炎糖丸—部分加强；乙脑疫苗—加强；甲肝疫苗；</td>
                </tr>
                <tr>
                    <td>3岁</td>
                    <td>A群流脑疫苗—第三针（也可用A+C群流脑疫苗）</td>
                </tr>
                <tr>
                    <td>4岁</td>
                    <td>脊髓灰质炎疫苗—加强针；</td>
                </tr>
                <tr>
                    <td>6岁</td>
                    <td>麻疹疫苗—加强针；白破二联疫苗—加强针；乙脑疫苗—第三针；A群流脑疫苗—第四针；</td>
                </tr>
                <tr>
                    <td>12岁</td>
                    <td>卡介苗—加强针</td>
                </tr>
            </table>
            <h2>二类疫苗</h2>
            <table>
                <tr>
                    <td>A+C群流脑疫苗</td>
                    <td>3周岁注射1针次，6、9周岁各加强一针。</td>
                </tr>
                <tr>
                    <td>无细胞百白破疫苗</td>
                    <td>可替代全细胞百白破疫苗，接种程序同全细胞百白破疫苗。</td>
                </tr>
                <tr>
                    <td>麻腮风疫苗</td>
                    <td>1.5-2周岁注射一针，基础免疫后4年加强1针。</td>
                </tr>
                <tr>
                    <td>甲肝减毒活疫苗或甲肝灭活疫苗</td>
                    <td>甲肝减毒活疫苗接种时间是2岁时注射1针，4年后加强1针。灭活疫苗1-16岁接种2针，间隔6个月，16岁以上接种1针。</td>
                </tr>
                <tr>
                    <td>水痘疫苗</td>
                    <td>1-12岁接种1针次。</td>
                </tr>
                <tr>
                    <td>B型流感嗜血杆菌苗</td>
                    <td>2、4、6月龄各注射一次，12月龄以上接种一针即可。</td>
                </tr>
                <tr>
                    <td>流行性感冒疫苗</td>
                    <td>1-3周岁每年注射2针，间隔1个月。3周岁以上每年接种1次即可。</td>
                </tr>
            </table>
        </ui-article>
    </my-page>
</template>

<script>
    export default {
        data () {
            return {
            }
        },
        mounted() {
        },
        methods: {
        }
    }
</script>

<style lang="scss" scoped>
</style>
